export const columns = [
  {
    field: "name",
    headerName: "Name",
    align: "center",
    headerAlign: "center",
    minWidth: 50,
  },
  {
    field: "manufacturer",
    headerName: "manufacturer",
    align: "center",
    headerAlign: "center",
    minWidth: 120,
  },
  {
    field: "originType",
    headerName: "originType",
    align: "center",
    headerAlign: "center",
    minWidth: 100,
  },
  {
    field: "productionDate",
    headerName: "productionDate",
    align: "center",
    headerAlign: "center",
    minWidth: 200,
  },
  {
    field: "expirationDate",
    headerName: "expirationDate",
    align: "center",
    headerAlign: "center",
    minWidth: 200,
  },
  {
    field: "price",
    headerName: "price",
    align: "center",
    headerAlign: "center",
    minWidth: 100,
  },
  {
    field: "discount",
    headerName: "discount",
    flex: 1,
    align: "center",
    headerAlign: "center",
    minWidth: 100,
  },
  {
    field: "description",
    headerName: "description",
    flex: 1,
    align: "center",
    headerAlign: "center",
    minWidth: 100,
  },
  {
    field: "stock",
    headerName: "stock",
    flex: 1,
    align: "center",
    headerAlign: "center",
    minWidth: 50,
  },
  {
    field: "sold",
    headerName: "sold",
    flex: 1,
    align: "center",
    headerAlign: "center",
    type: "number",
    minWidth: 50,
  },
  {
    field: "isVisible",
    headerName: "isVisible",
    flex: 1,
    align: "center",
    headerAlign: "center",
    type: "number",
    minWidth: 100,
  },
];
