export const columns = [
  {
    field: "_id",
    headerName: "ID",
    align: "center",
    headerAlign: "center",
    minWidth: 50,
  },
  {
    field: "name",
    headerName: "Name",
    align: "center",
    headerAlign: "center",
    minWidth: 150,
  },
  {
    field: "ownerName",
    headerName: "Owner Name",
    align: "center",
    headerAlign: "center",
    minWidth: 150,
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
    align: "center",
    headerAlign: "center",
    minWidth: 200,
  },
  {
    field: "role",
    headerName: "Role",
    align: "center",
    headerAlign: "center",
    minWidth: 100,
  },

  {
    field: "phone",
    headerName: "Phone",
    flex: 1,
    align: "center",
    headerAlign: "center",
    minWidth: 150,
  },
  {
    field: "identificationNumber",
    headerName: "Identification Number",
    flex: 1,
    align: "center",
    headerAlign: "center",
    type: "number",
    minWidth: 100,
  },
  {
    field: "registrationNumber",
    headerName: "Registration Number",
    flex: 1,
    align: "center",
    headerAlign: "center",
    type: "number",
    minWidth: 150,
  },

  {
    field: "city",
    headerName: "City",
    align: "center",
    headerAlign: "center",
    minWidth: 100,
  },
  {
    field: "governorate",
    headerName: "Governorate",
    align: "center",
    headerAlign: "center",
    minWidth: 100,
  },
  // {
  //   field: "active",
  //   headerName: "Active",
  //   align: "center",
  //   headerAlign: "center",
  //   minWidth: 100,
  // },
];
