export const rows = [
  {
    id: 1,
    registerId: 2224,
    name: 'Refai',
    Email: 'refai@gmail.com',
    Age: '22',
    Phone: '01149803891',
    Address: 777777,
    Access: 'Manager',
    ZipCode: 11111,
  },
  {
    id: 2,
    registerId: 2224,
    name: 'Refai',
    Email: 'refai@gmail.com',
    Age: '22',
    Phone: '01149803891',
    Address: 777777,
    Access: 'Manager',
    ZipCode: 11111,
  },
  {
    id: 3,
    registerId: 2224,
    name: 'Refai',
    Email: 'refai@gmail.com',
    Age: '22',
    Phone: '01149803891',
    Address: 777777,
    Access: 'Manager',
    ZipCode: 11111,
  },
  {
    id: 4,
    registerId: 2224,
    name: 'Refai',
    Email: 'refai@gmail.com',
    Age: '22',
    Phone: '01149803891',
    Address: 777777,
    Access: 'Manager',
    ZipCode: 11111,
  },
  {
    id: 5,
    registerId: 2224,
    name: 'Refai',
    Email: 'refai@gmail.com',
    Age: '22',
    Phone: '01149803891',
    Address: 777777,
    Access: 'Manager',
    ZipCode: 11111,
  },
  {
    id: 6,
    registerId: 2224,
    name: 'Refai',
    Email: 'refai@gmail.com',
    Age: '22',
    Phone: '01149803891',
    Address: 777777,
    Access: 'Manager',
    ZipCode: 11111,
  },
  {
    id: 7,
    registerId: 2224,
    name: 'Refai',
    Email: 'refai@gmail.com',
    Age: '22',
    Phone: '01149803891',
    Address: 777777,
    Access: 'Manager',
    ZipCode: 11111,
  },
  {
    id: 8,
    registerId: 2224,
    name: 'Refai',
    Email: 'refai@gmail.com',
    Age: '22',
    Phone: '01149803891',
    Address: 777777,
    Access: 'Manager',
    ZipCode: 11111,
  },
];

export const columns = [
  {
    field: 'id',
    headerName: 'ID',
    align: 'center',
    headerAlign: 'center',
    minWidth: 10, // تحديد عرض أدنى للعمود
  },
  {
    field: 'registerId',
    headerName: 'Register ID',
    align: 'center',
    headerAlign: 'center',
    minWidth: 100, // تحديد عرض أدنى للعمود
  },
  {
    field: 'name',
    headerName: 'Name',
    align: 'center',
    headerAlign: 'center',
    minWidth: 150, // تحديد عرض أدنى للعمود
  },
  {
    field: 'Email',
    headerName: 'Email',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    minWidth: 200, // تحديد عرض أدنى للعمود
  },
  {
    field: 'Age',
    headerName: 'Age',
    align: 'center',
    headerAlign: 'center',
    minWidth: 70, // تحديد عرض أدنى للعمود
  },
  {
    field: 'Phone',
    headerName: 'Phone',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    minWidth: 150, // تحديد عرض أدنى للعمود
  },
  {
    field: 'Address',
    headerName: 'Address',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    type: 'number',
    minWidth: 100, // تحديد عرض أدنى للعمود
  },
  {
    field: 'ZipCode',
    headerName: 'Zip Code',
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    type: 'number',
    minWidth: 150, // تحديد عرض أدنى للعمود
  },
];
